package roboyard.eclabs.data;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Contains solution data for all levels including optimal move counts.
 * This data is used for:
 * - Achievement validation (e.g., 3 stars on levels with 10+ moves)
 * - Testing and verification
 * - Display of optimal solutions
 * 
 * Data is generated by running LevelSolutionGeneratorTest which solves all levels
 * and records the solutions.
 */
public class LevelSolutionData {
    
    /**
     * Represents a single solution for a level
     */
    public static class Solution {
        public final String moves;  // Solution string like "R1U,B2L,G3D"
        public final int moveCount; // Number of moves in this solution
        
        public Solution(String moves, int moveCount) {
            this.moves = moves;
            this.moveCount = moveCount;
        }
    }
    
    /**
     * Represents all data for a single level
     */
    public static class LevelData {
        public final int levelId;
        public final int optimalMoves;           // Minimum moves needed
        public final List<Solution> solutions;   // All known solutions (may have multiple)
        
        public LevelData(int levelId, int optimalMoves) {
            this.levelId = levelId;
            this.optimalMoves = optimalMoves;
            this.solutions = new ArrayList<>();
        }
        
        public void addSolution(String moves, int moveCount) {
            solutions.add(new Solution(moves, moveCount));
        }
    }
    
    private static Map<Integer, LevelData> levelDataMap;
    
    /**
     * Get the optimal move count for a level
     * @param levelId The level ID (1-140)
     * @return The optimal move count, or -1 if not found
     */
    public static int getOptimalMoves(int levelId) {
        initializeIfNeeded();
        LevelData data = levelDataMap.get(levelId);
        return data != null ? data.optimalMoves : -1;
    }
    
    /**
     * Check if a level requires at least the specified number of moves
     * @param levelId The level ID
     * @param minMoves Minimum moves threshold
     * @return true if the level requires at least minMoves
     */
    public static boolean requiresAtLeastMoves(int levelId, int minMoves) {
        int optimal = getOptimalMoves(levelId);
        return optimal >= minMoves;
    }
    
    /**
     * Get all levels that require at least the specified number of moves
     * @param minMoves Minimum moves threshold
     * @return List of level IDs
     */
    public static List<Integer> getLevelsWithMinMoves(int minMoves) {
        initializeIfNeeded();
        List<Integer> result = new ArrayList<>();
        for (LevelData data : levelDataMap.values()) {
            if (data.optimalMoves >= minMoves) {
                result.add(data.levelId);
            }
        }
        return result;
    }
    
    /**
     * Get all data for a level
     * @param levelId The level ID
     * @return LevelData or null if not found
     */
    public static LevelData getLevelData(int levelId) {
        initializeIfNeeded();
        return levelDataMap.get(levelId);
    }
    
    /**
     * Get all level data
     * @return Map of level ID to LevelData
     */
    public static Map<Integer, LevelData> getAllLevelData() {
        initializeIfNeeded();
        return new HashMap<>(levelDataMap);
    }
    
    private static void initializeIfNeeded() {
        if (levelDataMap == null) {
            levelDataMap = new HashMap<>();
            initializeLevelData();
        }
    }
    
    /**
     * Initialize level data with optimal move counts.
     * This data is generated by LevelSolutionGeneratorTest.
     * 
     * TODO: This will be populated by running the test that solves all levels.
     * For now, placeholder data is used.
     */
    private static void initializeLevelData() {
        // Placeholder data - will be replaced by actual data from test run
        // Format: addLevel(levelId, optimalMoves, solutionString)
        
        // These values will be populated by running LevelSolutionGeneratorTest
        // which solves each level and records the optimal move count and solution
        
        addLevel(1, 2, "1 -> Up,1 -> Right");
        addLevel(2, 2, "2 -> Right,2 -> Down");
        addLevel(3, 3, "1 -> Down,1 -> Right,1 -> Down");
        addLevel(4, 3, "1 -> Right,1 -> Up,1 -> Left");
        addLevel(5, 3, "0 -> Right,0 -> Down,0 -> Left");
        addLevel(6, 2, "0 -> Right,0 -> Down");
        addLevel(7, 3, "3 -> Right,3 -> Up,1 -> Right");
        addLevel(8, 3, "3 -> Left,3 -> Down,3 -> Right");
        addLevel(9, 3, "3 -> Down,2 -> Down,2 -> Left");
        addLevel(10, 2, "2 -> Right,2 -> Down");
        addLevel(11, 4, "2 -> Right,3 -> Right,3 -> Down,2 -> Left");
        addLevel(12, 2, "2 -> Down,2 -> Right");
        addLevel(13, 2, "3 -> Right,3 -> Down");
        addLevel(14, 2, "1 -> Down,1 -> Left");
        addLevel(15, 6, "0 -> Up,3 -> Up,3 -> Left,3 -> Up,1 -> Left,1 -> Up");
        addLevel(16, 6, "2 -> Down,1 -> Down,1 -> Right,1 -> Down,1 -> Left,1 -> Up");
        addLevel(17, 5, "3 -> Right,2 -> Right,3 -> Down,3 -> Left,3 -> Up");
        addLevel(18, 4, "1 -> Down,0 -> Down,0 -> Left,0 -> Up");
        addLevel(19, 4, "2 -> Left,1 -> Up,1 -> Left,1 -> Up");
        addLevel(20, 5, "2 -> Down,2 -> Right,2 -> Up,2 -> Right,1 -> Right");
        addLevel(21, 6, "1 -> Right,2 -> Right,2 -> Up,2 -> Left,2 -> Up,2 -> Right");
        addLevel(22, 5, "0 -> Up,2 -> Right,2 -> Down,3 -> Right,3 -> Up");
        addLevel(23, 6, "3 -> Up,3 -> Right,1 -> Up,1 -> Left,1 -> Up,1 -> Right");
        addLevel(24, 6, "0 -> Right,2 -> Right,2 -> Up,0 -> Left,2 -> Down,0 -> Right");
        addLevel(25, 6, "1 -> Down,1 -> Left,0 -> Left,0 -> Down,0 -> Right,0 -> Up");
        addLevel(26, 7, "0 -> Down,0 -> Right,0 -> Up,2 -> Up,3 -> Right,3 -> Down,3 -> Left");
        addLevel(27, 5, "2 -> Up,2 -> Left,2 -> Down,2 -> Right,2 -> Up");
        addLevel(28, 4, "3 -> Left,3 -> Down,3 -> Right,3 -> Up");
        addLevel(29, 6, "3 -> Left,2 -> Left,2 -> Up,2 -> Left,3 -> Up,3 -> Right");
        addLevel(30, 5, "3 -> Up,3 -> Left,3 -> Down,1 -> Right,1 -> Down");
        addLevel(31, 6, "2 -> Right,2 -> Up,0 -> Right,0 -> Up,0 -> Right,0 -> Up");
        addLevel(32, 3, "0 -> Down,3 -> Left,3 -> Down");
        addLevel(33, 6, "0 -> Left,0 -> Up,3 -> Left,3 -> Up,3 -> Right,3 -> Down");
        addLevel(34, 4, "3 -> Left,3 -> Up,3 -> Right,3 -> Down");
        addLevel(35, 6, "2 -> Right,1 -> Right,1 -> Down,1 -> Left,2 -> Down,2 -> Left");
        addLevel(36, 6, "2 -> Up,2 -> Left,1 -> Left,1 -> Up,2 -> Right,2 -> Down");
        addLevel(37, 5, "1 -> Right,1 -> Up,1 -> Right,1 -> Down,1 -> Left");
        addLevel(38, 5, "2 -> Up,1 -> Left,1 -> Up,1 -> Left,1 -> Down");
        addLevel(39, 4, "1 -> Up,2 -> Left,2 -> Down,2 -> Left");
        addLevel(40, 6, "2 -> Down,3 -> Up,3 -> Right,3 -> Up,3 -> Left,3 -> Down");
        addLevel(41, 10, "2 -> Up,2 -> Left,2 -> Up,2 -> Left,0 -> Right,0 -> Up,0 -> Left,0 -> Up,0 -> Left,0 -> Down");
        addLevel(42, 9, "3 -> Up,3 -> Right,3 -> Down,3 -> Left,2 -> Down,2 -> Right,3 -> Right,2 -> Down,3 -> Left");
        addLevel(43, 10, "1 -> Right,1 -> Down,1 -> Left,1 -> Down,2 -> Right,2 -> Down,2 -> Left,1 -> Up,1 -> Left,1 -> Down");
        addLevel(44, 9, "2 -> Right,2 -> Down,2 -> Right,1 -> Down,1 -> Left,0 -> Up,0 -> Left,0 -> Down,0 -> Right");
        addLevel(45, 10, "3 -> Down,3 -> Right,3 -> Up,1 -> Down,1 -> Right,3 -> Down,3 -> Right,1 -> Up,3 -> Left,1 -> Down");
        addLevel(46, 6, "2 -> Up,2 -> Right,0 -> Up,0 -> Right,0 -> Up,0 -> Left");
        addLevel(47, 10, "1 -> Left,1 -> Up,0 -> Left,0 -> Up,0 -> Right,3 -> Up,3 -> Right,0 -> Down,1 -> Left,1 -> Down");
        addLevel(48, 10, "0 -> Left,0 -> Up,0 -> Left,0 -> Down,1 -> Down,1 -> Right,1 -> Up,1 -> Left,0 -> Up,0 -> Right");
        addLevel(49, 9, "0 -> Down,3 -> Right,3 -> Down,3 -> Right,2 -> Right,2 -> Down,2 -> Right,2 -> Down,2 -> Left");
        addLevel(50, 8, "0 -> Right,0 -> Up,0 -> Right,0 -> Down,0 -> Right,2 -> Right,2 -> Down,0 -> Left");
        addLevel(51, 8, "1 -> Right,1 -> Up,1 -> Right,3 -> Right,3 -> Up,3 -> Right,3 -> Down,3 -> Left");
        addLevel(52, 8, "0 -> Down,2 -> Left,2 -> Down,2 -> Right,2 -> Up,3 -> Down,3 -> Right,3 -> Up");
        addLevel(53, 10, "1 -> Right,1 -> Up,0 -> Up,0 -> Right,2 -> Left,2 -> Up,0 -> Left,1 -> Left,1 -> Down,1 -> Right");
        addLevel(54, 10, "3 -> Down,3 -> Right,3 -> Down,3 -> Left,3 -> Down,3 -> Left,3 -> Up,3 -> Left,2 -> Up,3 -> Right");
        addLevel(55, 10, "2 -> Down,1 -> Down,1 -> Right,2 -> Up,2 -> Right,1 -> Left,0 -> Down,0 -> Left,0 -> Up,0 -> Right");
        addLevel(56, 8, "2 -> Up,1 -> Up,1 -> Right,1 -> Down,3 -> Right,1 -> Up,1 -> Left,1 -> Up");
        addLevel(57, 7, "1 -> Left,2 -> Down,2 -> Right,2 -> Up,0 -> Down,0 -> Right,0 -> Up");
        addLevel(58, 7, "1 -> Right,3 -> Right,3 -> Up,3 -> Right,3 -> Up,3 -> Right,3 -> Down");
        addLevel(59, 8, "2 -> Up,1 -> Right,1 -> Up,2 -> Right,2 -> Down,1 -> Right,2 -> Up,2 -> Left");
        addLevel(60, 11, "0 -> Down,3 -> Down,3 -> Left,3 -> Up,3 -> Right,3 -> Up,2 -> Up,2 -> Right,2 -> Down,2 -> Right,2 -> Up");
        addLevel(61, 10, "0 -> Up,0 -> Right,0 -> Down,2 -> Down,2 -> Right,0 -> Up,2 -> Left,0 -> Left,0 -> Up,0 -> Left");
        addLevel(62, 12, "2 -> Left,2 -> Down,1 -> Left,1 -> Down,1 -> Right,3 -> Left,3 -> Up,1 -> Left,3 -> Left,3 -> Up,3 -> Right,3 -> Down");
        addLevel(63, 8, "2 -> Down,2 -> Left,1 -> Right,0 -> Left,0 -> Up,0 -> Right,0 -> Up,0 -> Right");
        addLevel(64, 7, "2 -> Right,0 -> Up,0 -> Right,0 -> Up,3 -> Right,0 -> Down,0 -> Left");
        addLevel(65, 8, "0 -> Up,1 -> Down,1 -> Right,1 -> Up,1 -> Left,2 -> Left,2 -> Up,2 -> Right");
        addLevel(66, 8, "1 -> Up,1 -> Left,1 -> Down,1 -> Right,0 -> Up,0 -> Left,0 -> Down,1 -> Left");
        addLevel(67, 13, "1 -> Up,3 -> Right,3 -> Up,3 -> Right,2 -> Down,2 -> Right,2 -> Down,2 -> Left,1 -> Down,1 -> Right,1 -> Up,2 -> Right,2 -> Up");
        addLevel(68, 9, "1 -> Down,1 -> Left,1 -> Up,1 -> Left,1 -> Down,1 -> Left,1 -> Down,1 -> Right,1 -> Down");
        addLevel(69, 8, "3 -> Right,2 -> Right,2 -> Up,1 -> Up,1 -> Right,1 -> Up,1 -> Left,1 -> Up");
        addLevel(70, 6, "3 -> Right,3 -> Down,3 -> Left,2 -> Up,1 -> Right,1 -> Up");
        addLevel(71, 7, "0 -> Down,0 -> Left,0 -> Down,0 -> Right,1 -> Left,1 -> Down,0 -> Left");
        addLevel(72, 10, "2 -> Left,2 -> Down,2 -> Right,2 -> Up,2 -> Left,0 -> Left,0 -> Down,0 -> Right,0 -> Up,0 -> Left");
        addLevel(73, 9, "0 -> Up,0 -> Right,1 -> Up,1 -> Right,3 -> Left,3 -> Down,3 -> Right,3 -> Up,3 -> Right");
        addLevel(74, 7, "3 -> Right,0 -> Right,0 -> Up,0 -> Left,3 -> Left,0 -> Up,3 -> Right");
        addLevel(75, 11, "2 -> Left,2 -> Up,2 -> Left,2 -> Up,2 -> Right,0 -> Left,0 -> Up,0 -> Left,0 -> Up,0 -> Right,0 -> Up");
        addLevel(76, 8, "0 -> Down,0 -> Right,2 -> Down,2 -> Left,2 -> Down,0 -> Left,0 -> Down,0 -> Left");
        addLevel(77, 9, "2 -> Left,2 -> Down,2 -> Right,2 -> Up,2 -> Left,1 -> Down,1 -> Right,1 -> Up,2 -> Right");
        addLevel(78, 10, "0 -> Left,3 -> Down,2 -> Down,0 -> Right,0 -> Down,2 -> Right,2 -> Down,2 -> Left,2 -> Up,2 -> Left");
        addLevel(79, 10, "0 -> Left,0 -> Up,2 -> Left,2 -> Up,2 -> Right,2 -> Down,2 -> Left,3 -> Down,2 -> Right,2 -> Up");
        addLevel(80, 9, "0 -> Down,1 -> Down,1 -> Left,2 -> Down,2 -> Left,2 -> Up,1 -> Right,2 -> Down,1 -> Left");
        addLevel(81, 7, "2 -> Down,2 -> Right,2 -> Up,2 -> Right,2 -> Down,2 -> Left,2 -> Up");
        addLevel(82, 8, "3 -> Down,1 -> Left,1 -> Up,1 -> Right,1 -> Up,3 -> Up,3 -> Right,1 -> Down");
        addLevel(83, 9, "2 -> Down,0 -> Left,0 -> Down,0 -> Right,0 -> Down,0 -> Left,0 -> Down,0 -> Right,0 -> Up");
        addLevel(84, 8, "2 -> Right,0 -> Down,0 -> Right,0 -> Down,0 -> Left,0 -> Up,2 -> Left,0 -> Down");
        addLevel(85, 10, "3 -> Right,3 -> Down,3 -> Left,1 -> Right,1 -> Down,1 -> Left,1 -> Up,0 -> Down,0 -> Left,0 -> Up");
        addLevel(86, 7, "2 -> Right,2 -> Down,2 -> Left,1 -> Down,1 -> Left,1 -> Up,1 -> Right");
        addLevel(87, 6, "1 -> Up,1 -> Right,2 -> Left,2 -> Up,2 -> Right,2 -> Down");
        addLevel(88, 8, "2 -> Right,2 -> Up,2 -> Right,1 -> Right,1 -> Up,1 -> Right,1 -> Down,1 -> Left");
        addLevel(89, 7, "3 -> Down,1 -> Down,1 -> Right,1 -> Up,1 -> Right,3 -> Up,3 -> Left");
        addLevel(90, 7, "0 -> Down,3 -> Up,3 -> Right,3 -> Down,3 -> Right,3 -> Down,3 -> Right");
        addLevel(91, 8, "0 -> Up,0 -> Left,0 -> Up,0 -> Left,2 -> Left,2 -> Up,2 -> Right,3 -> Up");
        addLevel(92, 9, "2 -> Up,2 -> Right,3 -> Left,3 -> Up,3 -> Left,1 -> Up,1 -> Right,3 -> Right,3 -> Up");
        addLevel(93, 10, "3 -> Left,1 -> Left,1 -> Down,1 -> Right,3 -> Right,1 -> Up,2 -> Left,2 -> Down,2 -> Right,3 -> Up");
        addLevel(94, 10, "1 -> Down,1 -> Left,2 -> Right,2 -> Down,2 -> Left,2 -> Up,0 -> Left,0 -> Down,0 -> Left,2 -> Down");
        addLevel(95, 8, "3 -> Up,2 -> Right,1 -> Right,1 -> Down,1 -> Left,2 -> Left,2 -> Up,2 -> Left");
        addLevel(96, 9, "2 -> Left,1 -> Left,3 -> Up,3 -> Right,3 -> Up,1 -> Right,1 -> Down,2 -> Right,2 -> Down");
        addLevel(97, 8, "1 -> Up,1 -> Left,0 -> Up,0 -> Left,0 -> Down,0 -> Right,3 -> Down,0 -> Left");
        addLevel(98, 9, "2 -> Up,2 -> Right,1 -> Up,1 -> Left,1 -> Down,1 -> Right,1 -> Down,1 -> Right,1 -> Down");
        addLevel(99, 10, "2 -> Right,2 -> Up,3 -> Down,3 -> Right,3 -> Up,3 -> Left,0 -> Up,0 -> Right,0 -> Up,3 -> Right");
        addLevel(100, 9, "1 -> Down,1 -> Right,1 -> Up,0 -> Left,2 -> Down,2 -> Left,2 -> Down,2 -> Right,2 -> Up");
        addLevel(101, 7, "1 -> Right,1 -> Down,1 -> Left,2 -> Right,2 -> Down,2 -> Left,2 -> Up");
        addLevel(102, 7, "0 -> Up,0 -> Left,2 -> Down,2 -> Right,2 -> Up,0 -> Right,0 -> Down");
        addLevel(103, 10, "3 -> Up,3 -> Right,0 -> Down,0 -> Left,2 -> Up,2 -> Left,2 -> Up,2 -> Right,2 -> Up,2 -> Right");
        addLevel(104, 9, "2 -> Down,2 -> Right,2 -> Down,2 -> Left,2 -> Down,0 -> Down,0 -> Left,0 -> Up,0 -> Right");
        addLevel(105, 10, "0 -> Left,0 -> Up,3 -> Left,3 -> Up,3 -> Left,3 -> Up,3 -> Right,2 -> Up,2 -> Left,3 -> Left");
        addLevel(106, 9, "0 -> Down,2 -> Up,2 -> Left,2 -> Down,3 -> Right,3 -> Down,0 -> Left,0 -> Up,3 -> Left");
        addLevel(107, 9, "3 -> Right,3 -> Down,0 -> Left,0 -> Up,3 -> Right,2 -> Right,2 -> Down,3 -> Left,3 -> Up");
        addLevel(108, 8, "1 -> Left,0 -> Left,0 -> Down,1 -> Right,2 -> Up,2 -> Left,2 -> Up,2 -> Right");
        addLevel(109, 11, "2 -> Up,2 -> Right,3 -> Left,3 -> Up,3 -> Right,3 -> Down,0 -> Left,0 -> Down,0 -> Right,3 -> Up,3 -> Left");
        addLevel(110, 8, "3 -> Up,0 -> Left,0 -> Down,0 -> Left,0 -> Up,0 -> Left,0 -> Down,0 -> Right");
        addLevel(111, 14, "2 -> Up,2 -> Right,2 -> Down,1 -> Right,1 -> Down,1 -> Left,3 -> Down,3 -> Right,3 -> Up,3 -> Right,3 -> Down,3 -> Right,3 -> Down,3 -> Left");
        addLevel(112, 13, "3 -> Left,3 -> Up,3 -> Right,3 -> Up,3 -> Right,1 -> Right,1 -> Down,1 -> Left,3 -> Left,3 -> Down,3 -> Right,1 -> Down,3 -> Left");
        addLevel(113, 15, "2 -> Down,2 -> Right,2 -> Down,2 -> Left,2 -> Down,2 -> Right,2 -> Up,2 -> Right,2 -> Down,3 -> Right,3 -> Down,3 -> Right,2 -> Up,3 -> Left,2 -> Down");
        addLevel(114, 16, "0 -> Left,0 -> Down,0 -> Left,2 -> Left,2 -> Up,2 -> Left,2 -> Down,1 -> Left,1 -> Up,1 -> Left,1 -> Down,2 -> Right,2 -> Down,0 -> Up,0 -> Right,0 -> Down");
        addLevel(115, 13, "1 -> Up,1 -> Left,1 -> Down,2 -> Down,2 -> Right,1 -> Up,0 -> Down,0 -> Left,1 -> Down,2 -> Up,2 -> Right,1 -> Up,0 -> Up");
        addLevel(116, 12, "3 -> Right,0 -> Right,0 -> Up,0 -> Right,1 -> Left,1 -> Up,1 -> Right,2 -> Left,2 -> Down,2 -> Left,2 -> Up,2 -> Right");
        addLevel(117, 11, "3 -> Up,3 -> Right,1 -> Right,1 -> Up,1 -> Right,1 -> Down,1 -> Left,0 -> Down,0 -> Right,0 -> Down,0 -> Left");
        addLevel(118, 12, "3 -> Down,2 -> Down,2 -> Left,0 -> Left,0 -> Up,2 -> Right,2 -> Up,3 -> Up,3 -> Right,2 -> Down,3 -> Left,2 -> Up");
        addLevel(119, 14, "3 -> Up,2 -> Left,2 -> Down,2 -> Left,3 -> Down,2 -> Right,3 -> Up,3 -> Right,3 -> Down,3 -> Left,2 -> Up,2 -> Right,2 -> Down,2 -> Right");
        addLevel(120, 16, "0 -> Right,0 -> Down,0 -> Left,3 -> Down,3 -> Right,3 -> Down,3 -> Left,2 -> Right,2 -> Down,2 -> Left,3 -> Up,3 -> Right,0 -> Right,0 -> Up,3 -> Left,2 -> Up");
        addLevel(121, 15, "3 -> Left,1 -> Left,1 -> Up,1 -> Left,1 -> Up,3 -> Up,2 -> Left,2 -> Up,2 -> Left,2 -> Up,1 -> Left,2 -> Down,2 -> Right,3 -> Down,2 -> Left");
        addLevel(122, 13, "0 -> Up,0 -> Right,3 -> Right,3 -> Down,3 -> Left,3 -> Down,0 -> Left,0 -> Up,0 -> Left,3 -> Up,0 -> Right,0 -> Down,0 -> Left");
        addLevel(123, 15, "0 -> Down,0 -> Left,0 -> Down,0 -> Left,2 -> Down,2 -> Right,0 -> Down,2 -> Left,0 -> Up,0 -> Right,2 -> Up,2 -> Left,2 -> Down,2 -> Right,2 -> Up");
        addLevel(124, 13, "3 -> Up,1 -> Right,2 -> Right,1 -> Up,1 -> Right,1 -> Up,1 -> Left,1 -> Down,1 -> Left,2 -> Up,2 -> Left,2 -> Down,1 -> Right");
        addLevel(125, 16, "1 -> Left,1 -> Down,1 -> Right,0 -> Up,0 -> Right,0 -> Up,0 -> Left,0 -> Down,0 -> Right,1 -> Down,1 -> Left,1 -> Up,0 -> Right,0 -> Down,0 -> Left,0 -> Up");
        addLevel(126, 12, "0 -> Right,3 -> Left,3 -> Down,2 -> Right,1 -> Down,1 -> Right,1 -> Up,1 -> Left,1 -> Up,2 -> Left,1 -> Down,1 -> Left");
        addLevel(127, 12, "3 -> Left,3 -> Up,3 -> Right,1 -> Up,1 -> Right,1 -> Down,2 -> Down,2 -> Right,2 -> Up,1 -> Up,2 -> Right,1 -> Down");
        addLevel(128, 12, "0 -> Down,3 -> Up,2 -> Up,2 -> Right,2 -> Down,2 -> Left,2 -> Up,1 -> Right,1 -> Down,0 -> Right,0 -> Up,2 -> Right");
        addLevel(129, 13, "0 -> Up,3 -> Down,3 -> Right,3 -> Up,1 -> Left,1 -> Down,1 -> Right,1 -> Down,1 -> Left,2 -> Up,2 -> Left,1 -> Up,2 -> Right");
        addLevel(130, 11, "2 -> Down,1 -> Left,1 -> Down,1 -> Right,2 -> Right,1 -> Down,2 -> Left,2 -> Up,2 -> Left,1 -> Up,2 -> Right");
        addLevel(131, 11, "1 -> Right,2 -> Down,2 -> Left,2 -> Down,2 -> Left,1 -> Left,1 -> Down,0 -> Down,1 -> Left,1 -> Up,0 -> Left");
        addLevel(132, 11, "3 -> Down,3 -> Left,3 -> Up,3 -> Right,0 -> Down,0 -> Left,0 -> Up,0 -> Right,0 -> Up,3 -> Left,3 -> Down");
        addLevel(133, 11, "2 -> Left,2 -> Down,1 -> Right,3 -> Left,3 -> Down,3 -> Right,0 -> Left,0 -> Down,0 -> Right,0 -> Up,0 -> Left");
        addLevel(134, 11, "0 -> Down,0 -> Left,0 -> Down,0 -> Left,1 -> Left,1 -> Down,1 -> Right,0 -> Down,0 -> Right,0 -> Up,0 -> Left");
        addLevel(135, 12, "1 -> Right,1 -> Down,1 -> Left,1 -> Down,1 -> Right,1 -> Down,0 -> Left,0 -> Down,0 -> Right,1 -> Up,1 -> Right,1 -> Down");
        addLevel(136, 18, "2 -> Up,2 -> Right,2 -> Up,2 -> Right,2 -> Down,0 -> Left,3 -> Down,2 -> Up,2 -> Left,2 -> Down,2 -> Right,0 -> Down,0 -> Right,2 -> Down,3 -> Right,3 -> Down,3 -> Left,3 -> Up");
        addLevel(137, 18, "2 -> Left,2 -> Up,3 -> Right,1 -> Right,1 -> Down,1 -> Left,0 -> Up,0 -> Left,0 -> Down,0 -> Right,0 -> Down,0 -> Right,3 -> Up,3 -> Left,0 -> Left,0 -> Down,0 -> Right,0 -> Up");
        addLevel(138, 17, "0 -> Up,0 -> Left,0 -> Down,0 -> Left,1 -> Up,1 -> Left,1 -> Up,1 -> Left,1 -> Up,2 -> Up,2 -> Left,2 -> Down,2 -> Left,2 -> Up,2 -> Left,2 -> Up,2 -> Right");
        addLevel(139, 17, "0 -> Left,0 -> Down,0 -> Right,0 -> Down,0 -> Left,0 -> Down,3 -> Down,3 -> Left,3 -> Up,1 -> Down,1 -> Left,1 -> Up,2 -> Up,2 -> Right,2 -> Down,2 -> Left,2 -> Up");

    }
    
    /**
     * Helper method to add level data
     */
    private static void addLevel(int levelId, int optimalMoves, String solution) {
        LevelData data = new LevelData(levelId, optimalMoves);
        if (solution != null && !solution.isEmpty()) {
            data.addSolution(solution, optimalMoves);
        }
        levelDataMap.put(levelId, data);
    }
    
    /**
     * Helper method to add level with multiple solutions
     */
    private static void addLevelWithSolutions(int levelId, int optimalMoves, String... solutions) {
        LevelData data = new LevelData(levelId, optimalMoves);
        for (String solution : solutions) {
            if (solution != null && !solution.isEmpty()) {
                data.addSolution(solution, optimalMoves);
            }
        }
        levelDataMap.put(levelId, data);
    }
}
