blank_issues_enabled: true
contact_links:
  - name: Questions and Support
    url: https://github.com/Eastcoast-Laboratories/Roboyard/discussions
    about: Ask questions and get support from the community